[package]
name = "dungeon_rogue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version = "0.6.1", features = ["dynamic"]}
bevy_ecs_tilemap = "0.5.0"
bevy_ecs_ldtk = "0.2.0"
bevy-inspector-egui = "0.9.0"
